language: node_js
node_js:
  - 16
services:
  - xvfb
dist: trusty
addons:
  chrome: stable
before_script:
  - yarn lint;
  - if [ "$TRAVIS_BRANCH" = "main" ]; then
      yarn build;
    else
      yarn build:dev;
    fi
  - CHROMEDRIVER_VERSION=LATEST_91 npm install chromedriver --save-dev
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9922 http://localhost &
script:
  - xvfb-run npm test