const ENERGY_MAX = 1000;
const ENERGY_REGEN_RATE = 100;
const HP_MAX = 1000;

const PLAYER_STATES = {
  DIZZY: "DIZZY",
  ESCAPING: "ESCAPING",
  FIGHTING: "FIGHTING",
  IDLE: "IDLE",
  PATROLLING: "PATROLLING",
  SHOULD_ESCAPE: "SHOULD_ESCAPE",
  WALKING_RANDOMLY: "WALKING_RANDOMLY",
};

export { ENERGY_MAX, ENERGY_REGEN_RATE, HP_MAX, PLAYER_STATES };
