module.exports = [
  {
    name: "player1",
    x: 13,
    y: 6,
    destX: null,
    destY: null,
    nextX: null,
    nextY: null,
    isOnline: false,
    socketId: null,
    direction: "east",
    hp: 50,
  },
  {
    name: "player2",
    x: 9,
    y: 4,
    destX: null,
    destY: null,
    nextX: null,
    nextY: null,
    isOnline: false,
    socketId: null,
    direction: "southEast",
    hp: 80,
  },
  {
    name: "player3",
    x: 19,
    y: 9,
    destX: null,
    destY: null,
    nextX: null,
    nextY: null,
    isOnline: false,
    socketId: null,
    direction: "south",
    hp: 75,
  },
  {
    name: "player4",
    x: 14,
    y: 12,
    destX: null,
    destY: null,
    isOnline: false,
    socketId: null,
    direction: "southWest",
    hp: 100,
  },
  {
    name: "player5",
    x: 12,
    y: 17,
    destX: null,
    destY: null,
    nextX: null,
    nextY: null,
    isOnline: false,
    socketId: null,
    direction: "west",
    hp: 100,
  },
  {
    name: "player6",
    x: 5,
    y: 12,
    destX: null,
    destY: null,
    nextX: null,
    nextY: null,
    isOnline: false,
    socketId: null,
    direction: "northWest",
    hp: 100,
  },
];
