module.exports = [
  {
    name: "player1",
    x: 13,
    y: 6,
    isMoving: false,
    isOnline: false,
    socketId: null,
    direction: "east",
  },
  {
    name: "player2",
    x: 9,
    y: 4,
    isMoving: false,
    isOnline: false,
    socketId: null,
    direction: "southEast",
  },
  {
    name: "player3",
    x: 19,
    y: 9,
    isMoving: false,
    isOnline: false,
    socketId: null,
    direction: "south",
  },
  {
    name: "player4",
    x: 14,
    y: 12,
    isMoving: false,
    isOnline: false,
    socketId: null,
    direction: "southWest",
  },
  {
    name: "player5",
    x: 12,
    y: 17,
    isMoving: false,
    isOnline: false,
    socketId: null,
    direction: "west",
  },
  {
    name: "player6",
    x: 5,
    y: 12,
    isMoving: false,
    isOnline: false,
    socketId: null,
    direction: "northWest",
  },
];
