const FRAME_IN_MS = 1000 / 30;

const PLAYER_STATES = {
  DIZZY: "DIZZY",
  ESCAPING: "ESCAPING",
  FIGHTING: "FIGHTING",
  IDLE: "IDLE",
  PATROLLING: "PATROLLING",
  SHOULD_ESCAPE: "SHOULD_ESCAPE",
  WALKING_RANDOMLY: "WALKING_RANDOMLY",
};

export { FRAME_IN_MS, PLAYER_STATES };
