module.exports = [
  {
    name: "player1",
    tileX: 13,
    tileY: 6,
    x: 256,
    y: 320,
    destTileX: null,
    destTileY: null,
    destX: null,
    destY: null,
    nextTileX: null,
    nextTileY: null,
    nextX: null,
    nextY: null,
    speed: 4,
    isOnline: false,
    socketId: null,
    direction: "east",
    hp: 50,
  },
  {
    name: "player2",
    tileX: 12,
    tileY: 10,
    x: 96,
    y: 368,
    destTileX: null,
    destTileY: null,
    destX: null,
    destY: null,
    nextTileX: null,
    nextTileY: null,
    nextX: null,
    nextY: null,
    speed: 4,
    isOnline: false,
    socketId: null,
    direction: "southEast",
    hp: 80,
  },
  {
    name: "player3",
    tileX: 19,
    tileY: 9,
    x: 352,
    y: 464,
    destTileX: null,
    destTileY: null,
    destX: null,
    destY: null,
    nextTileX: null,
    nextTileY: null,
    nextX: null,
    nextY: null,
    speed: 4,
    isOnline: false,
    socketId: null,
    direction: "south",
    hp: 75,
  },
  {
    name: "player4",
    tileX: 14,
    tileY: 12,
    x: 96,
    y: 432,
    destTileX: null,
    destTileY: null,
    destX: null,
    destY: null,
    nextTileX: null,
    nextTileY: null,
    nextX: null,
    nextY: null,
    speed: 4,
    isOnline: false,
    socketId: null,
    direction: "southWest",
    hp: 100,
  },
  {
    name: "player5",
    tileX: 12,
    tileY: 17,
    x: -128,
    y: 480,
    destTileX: null,
    destTileY: null,
    destX: null,
    destY: null,
    nextTileX: null,
    nextTileY: null,
    nextX: null,
    nextY: null,
    speed: 4,
    isOnline: false,
    socketId: null,
    direction: "west",
    hp: 100,
  },
  {
    name: "player6",
    tileX: 5,
    tileY: 12,
    x: -192,
    y: 288,
    destTileX: null,
    destTileY: null,
    destX: null,
    destY: null,
    nextTileX: null,
    nextTileY: null,
    nextX: null,
    nextY: null,
    speed: 4,
    isOnline: false,
    socketId: null,
    direction: "northWest",
    hp: 100,
  },
];
