module.exports = [
  {
    name: "player1",
    x: 224,
    y: 304,
    positionTile: { tileX: 13, tileY: 6 },
    dest: null,
    isWalking: false,
    isDead: false,
    settings: {
      dropSelectedOnMove: true,
      follow: true,
      fight: false,
    },
    selectedPlayer: null,
    selectedPlayerTile: null,
    attack: false,
    attackDelay: 0,
    attackMaxDelay: 30,
    next: null,
    speed: 2,
    isOnline: false,
    socketId: null,
    direction: "east",
    hp: 100,
  },
  {
    name: "player2",
    x: 64,
    y: 352,
    positionTile: { tileX: 12, tileY: 10 },
    dest: null,
    isWalking: false,
    isDead: false,
    settings: {
      dropSelectedOnMove: true,
      follow: false,
      fight: false,
    },
    selectedPlayer: null,
    selectedPlayerTile: null,
    attack: false,
    attackDelay: 0,
    attackMaxDelay: 30,
    next: null,
    speed: 2,
    isOnline: false,
    socketId: null,
    direction: "southEast",
    hp: 100,
  },
  {
    name: "player3",
    x: 320,
    y: 448,
    positionTile: { tileX: 19, tileY: 9 },
    dest: null,
    isWalking: false,
    isDead: false,
    settings: {
      dropSelectedOnMove: true,
      follow: false,
      fight: true,
    },
    selectedPlayer: null,
    selectedPlayerTile: null,
    attack: false,
    attackDelay: 0,
    attackMaxDelay: 30,
    next: null,
    speed: 2,
    isOnline: false,
    socketId: null,
    direction: "south",
    hp: 100,
  },
  {
    name: "player4",
    x: 64,
    y: 416,
    positionTile: { tileX: 14, tileY: 12 },
    dest: null,
    isWalking: false,
    isDead: false,
    settings: {
      dropSelectedOnMove: true,
      follow: false,
      fight: true,
    },
    selectedPlayer: null,
    selectedPlayerTile: null,
    attack: false,
    attackDelay: 0,
    attackMaxDelay: 30,
    next: null,
    speed: 2,
    isOnline: false,
    socketId: null,
    direction: "southWest",
    hp: 100,
  },
  {
    name: "player5",
    x: -160,
    y: 464,
    positionTile: { tileX: 12, tileY: 17 },
    dest: null,
    isWalking: false,
    isDead: false,
    settings: {
      dropSelectedOnMove: true,
      follow: false,
      fight: true,
    },
    selectedPlayer: null,
    selectedPlayerTile: null,
    attack: false,
    attackDelay: 0,
    attackMaxDelay: 30,
    next: null,
    speed: 2,
    isOnline: false,
    socketId: null,
    direction: "west",
    hp: 100,
  },
  {
    name: "player6",
    x: -224,
    y: 272,
    positionTile: { tileX: 5, tileY: 12 },
    dest: null,
    isWalking: false,
    isDead: false,
    settings: {
      dropSelectedOnMove: true,
      follow: false,
      fight: true,
    },
    selectedPlayer: null,
    selectedPlayerTile: null,
    attack: false,
    attackDelay: 0,
    attackMaxDelay: 30,
    next: null,
    speed: 2,
    isOnline: false,
    socketId: null,
    direction: "northWest",
    hp: 100,
  },
];
