# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: browser-actions/setup-chrome@latest
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        cache: 'yarn'
        
    - name: Install dependencies
      run: yarn --frozen-lockfile
      
    - name: Lint
      run: yarn lint
      
    - name: Build dev version
      if: github.ref == 'refs/heads/main'
      run: yarn build:dev
    - name: Build prod version
      if: github.ref != 'refs/heads/main'
      run: yarn build
      
    - name: Test
      run: yarn test
