name: Node.js CI

on:
  push:
    branches: [staging]
  pull_request:
    branches: [staging]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: setup-chromedriver
        uses: nanasess/setup-chromedriver@v1.0.1
        with:
          chromedriver-version: "97"
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.13.x"
          cache: "yarn"

      - name: Install dependencies
        run: yarn --immutable

      - name: Build test version
        run: yarn build:test

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test

      - name: Build dev version
        if: github.ref != 'refs/heads/main'
        run: yarn build:dev
      - name: Build prod version
        if: github.ref == 'refs/heads/main'
        run: yarn build
